/**
 * Auflistung sämtlicher existierender Geschäftsobjekte.
 *
 * veröffentlicht am 17. Januar 2018
 * [ENUM BOTyp](https://www.bo4e.de/dokumentation/enumerations/enum-botyp)
 */
export enum BoTyp {
    MARKTLOKATION = 'MARKTLOKATION',
    MESSLOKATION= 'MESSLOKATION',
    GESCHAEFTSPARTNER = 'GESCHAEFTSPARTNER',
    ZAEHLER = 'ZAEHLER',
    ANSPRECHPARTNER = 'ANSPRECHPARTNER',
    ANGEBOT='ANGEBOT',
    MARKTTEILNEHMER = 'MARKTTEILNEHMER',
    ENERGIEMENGE = 'ENERGIEMENGE',
    KOSTEN = 'KOSTEN',
    AUSSCHREIBUNG = 'AUSSCHREIBUNG',
    PREISBLATT = 'PREISBLATT',
    PREISBLATTNETZNUTZUNG = 'PREISBLATTNETZNUTZUNG',
    PREISBLATTMESSUNG = 'PREISBLATTMESSUNG',
    PREISBLATTDIENSTLEISTUNG = 'PREISBLATTDIENSTLEISTUNG',
    PREISBLATTUMLAGEN = 'PREISBLATTUMLAGEN',
    PREISBLATTKONZESSIONSABGABE = 'PREISBLATTKONZESSIONSABGABE',
    TARIFINFO = 'TARIFINFO',
    TARIFKOSTEN = 'TARIFKOSTEN',
    RECHNUNG = 'RECHNUNG',
    NETZNUTZUNGSRECHNUNG = 'NETZNUTZUNGSRECHNUNG',
    TARIFPREISBLATT = 'TARIFPREISBLATT',
    REGIONALTARIF = 'REGIONALTARIF',
    ZEITREIHE = 'ZEITREIHE',
    // Nicht im Standard:
    LASTGANG = 'LASTGANG',
    LASTGANGKOMPAKT = 'LASTGANGKOMPAKT',
    REGION = 'REGION',
    VERTRAG = 'VERTRAG',
    STANDORTEIGENSCHAFTEN = 'STANDORTEIGENSCHAFTEN',
    FREMDKOSTEN = 'FREMDKOSTEN',
    BUENDELVERTRAG = 'BUENDELVERTRAG',
    PREISBLATTHARDWARE = 'PREISBLATTHARDWARE',
    TARIF = 'TARIF'
}
