import {EnumLabels} from './util/enum-labels';
import {ImmutableMap} from './util/immutable-map';
import {Sparte} from './sparte.enum';

/**
 * Kundengruppe für eine Marktlokation (orientiert sich an den Standard-Lastprofilen).
 *
 * veröffentlicht am 11. April 2018
 *
 * @see [ENUM Kundengruppe](https://www.bo4e.de/dokumentation/enumerations/enum-kundengruppe)
 */
export enum Kundengruppe {
  RLM = 'RLM',
  RLM_KOMMUNAL = 'RLM_KOMMUNAL',
  SLP_KOMMUNAL = 'SLP_KOMMUNAL',
  SLP_S_G0 = 'SLP_S_G0',
  SLP_S_G1 = 'SLP_S_G1',
  SLP_S_G2 = 'SLP_S_G2',
  SLP_S_G3 = 'SLP_S_G3',
  SLP_S_G4 = 'SLP_S_G4',
  SLP_S_G5 = 'SLP_S_G5',
  SLP_S_G6 = 'SLP_S_G6',
  SLP_S_G7 = 'SLP_S_G7',
  SLP_S_L0 = 'SLP_S_L0',
  SLP_S_L1 = 'SLP_S_L1',
  SLP_S_L2 = 'SLP_S_L2',
  SLP_S_H0 = 'SLP_S_H0',
  SLP_S_SB = 'SLP_S_SB',
  SLP_S_HZ = 'SLP_S_HZ',
  SLP_S_WP = 'SLP_S_WP',
  SLP_S_EM = 'SLP_S_EM',
  SLP_S_HZ_GEM = 'SLP_S_HZ_GEM',
  SLP_G_GKO = 'SLP_G_GKO',
  SLP_G_STANDARD = 'SLP_G_STANDARD',
  SLP_G_GHA = 'SLP_G_GHA',
  SLP_G_GMK = 'SLP_G_GMK',
  SLP_G_GBD = 'SLP_G_GBD',
  SLP_G_GGA = 'SLP_G_GGA',
  SLP_G_GBH = 'SLP_G_GBH',
  SLP_G_GBA = 'SLP_G_GBA',
  SLP_G_GWA = 'SLP_G_GWA',
  SLP_G_GGB = 'SLP_G_GGB',
  SLP_G_GPD = 'SLP_G_GPD',
  SLP_G_GMF = 'SLP_G_GMF',
  SLP_G_HEF = 'SLP_G_HEF',
  SLP_G_HMF = 'SLP_G_HMF',
  SLP_G_HKO = 'SLP_G_HKO',
}

/**
 * Liefert kurze textuelle Repräsentationen der {@link Kostenklasse}.
 */
export const KundengruppeLabel: EnumLabels<Kundengruppe> = EnumLabels.of([
  [Kundengruppe.RLM, 'Kunde mit registrierender Leistungsmessung (kein SLP)'],
  [Kundengruppe.RLM_KOMMUNAL, 'Kommunale Abnahmestelle leistungsgemessen'],
  [Kundengruppe.SLP_KOMMUNAL, 'Kommunale Abnahmestelle nicht leistungsgemessen'],
  [Kundengruppe.SLP_S_G0, 'Gewerbe allgemein'],
  [Kundengruppe.SLP_S_G1, 'Werktags'],
  [Kundengruppe.SLP_S_G2, 'Verbrauch in Abendstunden'],
  [Kundengruppe.SLP_S_G3, 'Gewerbe durchlaufend'],
  [Kundengruppe.SLP_S_G4, 'Laden, Friseur'],
  [Kundengruppe.SLP_S_G5, 'Bäckerei mit Backstube'],
  [Kundengruppe.SLP_S_G6, 'Wochenendbetrieb'],
  [Kundengruppe.SLP_S_G7, 'Mobilfunksendestation'],
  [Kundengruppe.SLP_S_L0, 'Landwirtschaft allgemein'],
  [Kundengruppe.SLP_S_L1, 'Landwirtschaft mit Milchwirtschaft/Nebenerwerbs-Tierzucht'],
  [Kundengruppe.SLP_S_L2, 'Übrige Landwirtschaftsbetriebe'],
  [Kundengruppe.SLP_S_H0, 'Haushalt allgemein'],
  [Kundengruppe.SLP_S_SB, 'Straßenbeleuchtung'],
  [Kundengruppe.SLP_S_HZ, 'Nachtspeicherheizung'],
  [Kundengruppe.SLP_S_WP, 'Wärmepumpe'],
  [Kundengruppe.SLP_S_EM, 'Elektromobilität'],
  [Kundengruppe.SLP_S_HZ_GEM, 'Nachtspeicherheizung gemeinsame Messung'],
  [Kundengruppe.SLP_G_GKO, 'Gebietskörpersch., Kreditinst. u. Versich., Org. o. Erwerbszw. & öff. Einr.'],
  [Kundengruppe.SLP_G_STANDARD, 'Standardkundengruppe für Gas'],
  [Kundengruppe.SLP_G_GHA, 'Einzelhandel, Großhandel'],
  [Kundengruppe.SLP_G_GMK, 'Metall, Kfz'],
  [Kundengruppe.SLP_G_GBD, 'sonst. betr. Dienstleistungen'],
  [Kundengruppe.SLP_G_GGA, 'Beherbergung'],
  [Kundengruppe.SLP_G_GBH, 'Gaststätten'],
  [Kundengruppe.SLP_G_GBA, 'Bäckereien'],
  [Kundengruppe.SLP_G_GWA, 'Wäschereien'],
  [Kundengruppe.SLP_G_GGB, 'Gartenbau'],
  [Kundengruppe.SLP_G_GPD, 'Papier und Druck'],
  [Kundengruppe.SLP_G_GMF, 'haushaltsähnliche Gewerbebetriebe'],
  [Kundengruppe.SLP_G_HEF, 'Einfamilienhaushalt'],
  [Kundengruppe.SLP_G_HMF, 'Mehrfamilienhaushalt Gas'],
  [Kundengruppe.SLP_G_HKO, 'Kochgas'],
]);

/**
 * Liefert zurück, welche {@link Kundengruppe} in welcher {@link Sparte} verfügbar ist.
 */
export const KundengruppeSparte: ImmutableMap<Kundengruppe, Array<Sparte>> = ImmutableMap.of([
  [Kundengruppe.RLM, [Sparte.STROM, Sparte.GAS]],
  [Kundengruppe.RLM_KOMMUNAL, [Sparte.STROM, Sparte.GAS]],
  [Kundengruppe.SLP_KOMMUNAL, [Sparte.STROM, Sparte.GAS]],
  [Kundengruppe.SLP_KOMMUNAL, [Sparte.STROM, Sparte.GAS]],
  [Kundengruppe.SLP_S_G0, [Sparte.STROM]],
  [Kundengruppe.SLP_S_G1, [Sparte.STROM]],
  [Kundengruppe.SLP_S_G2, [Sparte.STROM]],
  [Kundengruppe.SLP_S_G3, [Sparte.STROM]],
  [Kundengruppe.SLP_S_G4, [Sparte.STROM]],
  [Kundengruppe.SLP_S_G5, [Sparte.STROM]],
  [Kundengruppe.SLP_S_G6, [Sparte.STROM]],
  [Kundengruppe.SLP_S_G7, [Sparte.STROM]],
  [Kundengruppe.SLP_S_L0, [Sparte.STROM]],
  [Kundengruppe.SLP_S_L1, [Sparte.STROM]],
  [Kundengruppe.SLP_S_L2, [Sparte.STROM]],
  [Kundengruppe.SLP_S_H0, [Sparte.STROM]],
  [Kundengruppe.SLP_S_SB, [Sparte.STROM]],
  [Kundengruppe.SLP_S_HZ, [Sparte.STROM]],
  [Kundengruppe.SLP_S_WP, [Sparte.STROM]],
  [Kundengruppe.SLP_S_EM, [Sparte.STROM]],
  [Kundengruppe.SLP_S_HZ_GEM, [Sparte.STROM]],
  [Kundengruppe.SLP_G_GKO, [Sparte.GAS]],
  [Kundengruppe.SLP_G_STANDARD, [Sparte.GAS]],
  [Kundengruppe.SLP_G_GHA, [Sparte.GAS]],
  [Kundengruppe.SLP_G_GMK, [Sparte.GAS]],
  [Kundengruppe.SLP_G_GBD, [Sparte.GAS]],
  [Kundengruppe.SLP_G_GGA, [Sparte.GAS]],
  [Kundengruppe.SLP_G_GBH, [Sparte.GAS]],
  [Kundengruppe.SLP_G_GBA, [Sparte.GAS]],
  [Kundengruppe.SLP_G_GWA, [Sparte.GAS]],
  [Kundengruppe.SLP_G_GGB, [Sparte.GAS]],
  [Kundengruppe.SLP_G_GPD, [Sparte.GAS]],
  [Kundengruppe.SLP_G_GMF, [Sparte.GAS]],
  [Kundengruppe.SLP_G_HEF, [Sparte.GAS]],
  [Kundengruppe.SLP_G_HMF, [Sparte.GAS]],
  [Kundengruppe.SLP_G_HKO, [Sparte.GAS]],
]);
