import {EnumLabels} from './util/enum-labels';

/**
 * Über dieses ENUM kann eine thematische Zuordnung, beispielsweise eines Ansprechpartners, vorgenommen werden.
 *
 * veröffentlicht am 17. Januar 2018
 *
 * @see [ENUM Themengebiet](https://www.bo4e.de/dokumentation/enumerations/enum-zustaendigkeit)
 */
export enum Themengebiet {
    ALLGEMEINER_INFORMATIONSAUSTAUSCH = 'ALLGEMEINER_INFORMATIONSAUSTAUSCH',
    AN_UND_ABMELDUNG = 'AN_UND_ABMELDUNG',
    ANSPRECHPARTNER_ALLGEMEIN = 'ANSPRECHPARTNER_ALLGEMEIN',
    ANSPRECHPARTNER_BDEW_DVGW = 'ANSPRECHPARTNER_BDEW_DVGW',
    ANSPRECHPARTNER_IT_TECHNIK = 'ANSPRECHPARTNER_IT_TECHNIK',
    BILANZIERUNG = 'BILANZIERUNG',
    BILANZKREISKOORDINATOR = 'BILANZKREISKOORDINATOR',
    BILANZKREISVERANTWORTLICHER = 'BILANZKREISVERANTWORTLICHER',
    DATENFORMATE_ZERTIFIKATE_VERSCHLUESSELUNGEN = 'DATENFORMATE_ZERTIFIKATE_VERSCHLUESSELUNGEN',
    DEBITORENMANAGEMENT = 'DEBITORENMANAGEMENT',
    DEMAND_SIDE_MANAGEMENT = 'DEMAND_SIDE_MANAGEMENT',
    EDI_VEREINBARUNG = 'EDI_VEREINBARUNG',
    EDIFACT = 'EDIFACT',
    ENERGIEDATENMANAGEMENT = 'ENERGIEDATENMANAGEMENT',
    FAHRPLANMANAGEMENT = 'FAHRPLANMANAGEMENT',
    ALOCAT = 'ALOCAT',
    APERAK = 'APERAK',
    CONTRL = 'CONTRL',
    INVOIC = 'INVOIC',
    MSCONS = 'MSCONS',
    ORDERS = 'ORDERS',
    ORDERSP = 'ORDERSP',
    REMADV = 'REMADV',
    UTILMD = 'UTILMD',
    GABI = 'GABI',
    GELI = 'GELI',
    GERAETERUECKGABE = 'GERAETERUECKGABE',
    GERAETEWECHSEL = 'GERAETEWECHSEL',
    GPKE = 'GPKE',
    INBETRIEBNAHME = 'INBETRIEBNAHME',
    KAPAZITAETSMANAGEMENT = 'KAPAZITAETSMANAGEMENT',
    KLAERFAELLE = 'KLAERFAELLE',
    LASTGAENGE_RLM = 'LASTGAENGE_RLM',
    LIEFERANTENRAHMENVERTRAG = 'LIEFERANTENRAHMENVERTRAG',
    LIEFERANTENWECHSEL = 'LIEFERANTENWECHSEL',
    MABIS = 'MABIS',
    MAHNWESEN = 'MAHNWESEN',
    MARKTGEBIETSVERANTWORTLICHER = 'MARKTGEBIETSVERANTWORTLICHER',
    MARKTKOMMUNIKATION = 'MARKTKOMMUNIKATION',
    MEHR_MINDERMENGEN = 'MEHR_MINDERMENGEN',
    MSB_MDL = 'MSB_MDL',
    NETZABRECHNUNG = 'NETZABRECHNUNG',
    NETZENTGELTE = 'NETZENTGELTE',
    NETZMANAGEMENT = 'NETZMANAGEMENT',
    RECHT = 'RECHT',
    REGULIERUNGSMANAGEMENT = 'REGULIERUNGSMANAGEMENT',
    REKLAMATIONEN = 'REKLAMATIONEN',
    SPERREN_ENTSPERREN_INKASSO = 'SPERREN_ENTSPERREN_INKASSO',
    STAMMDATEN = 'STAMMDATEN',
    STOERUNGSFAELLE = 'STOERUNGSFAELLE',
    TECHNISCHE_FRAGEN = 'TECHNISCHE_FRAGEN',
    UMSTELLUNG_INVOIC = 'UMSTELLUNG_INVOIC',
    VERSCHLUESSELUNG_SIGNATUR = 'VERSCHLUESSELUNG_SIGNATUR',
    VERTRAGSMANAGEMENT = 'VERTRAGSMANAGEMENT',
    VERTRIEB = 'VERTRIEB',
    WIM = 'WIM',
    ZAEHLERSTAENDE_SLP = 'ZAEHLERSTAENDE_SLP',
    ZAHLUNGSVERKEHR = 'ZAHLUNGSVERKEHR',
    ZUORDNUNGSVEREINBARUNG = 'ZUORDNUNGSVEREINBARUNG',
}

/**
 * Liefert kurze textuelle Repräsentationen des {@link Themengebiet}.
 */
export const ThemengebietLabel: EnumLabels<Themengebiet> = EnumLabels.of([
  [Themengebiet.ALLGEMEINER_INFORMATIONSAUSTAUSCH, 'Allgemeiner Informationsaustausch'],
  [Themengebiet.AN_UND_ABMELDUNG, 'An- und Abmeldung'],
  [Themengebiet.ANSPRECHPARTNER_ALLGEMEIN, 'Ansprechpartner Allgemein'],
  [Themengebiet.ANSPRECHPARTNER_BDEW_DVGW, 'Ansprechpartner BDEW/DVGW'],
  [Themengebiet.ANSPRECHPARTNER_IT_TECHNIK, 'Ansprechpartner IT/Technik'],
  [Themengebiet.BILANZIERUNG, 'Bilanzierung'],
  [Themengebiet.BILANZKREISKOORDINATOR, 'Bilanzkreiskoordinator'],
  [Themengebiet.BILANZKREISVERANTWORTLICHER, 'Bilanzkreisverantwortlicher'],
  [Themengebiet.DATENFORMATE_ZERTIFIKATE_VERSCHLUESSELUNGEN, 'Datenformate, Zertifikate, Verschlüsselungen'],
  [Themengebiet.DEBITORENMANAGEMENT, 'Debitorenmanagement'],
  [Themengebiet.DEMAND_SIDE_MANAGEMENT, 'Demand-Side-Management'],
  [Themengebiet.EDI_VEREINBARUNG, 'EDI-Vereinbarung'],
  [Themengebiet.EDIFACT, 'EDIFACT'],
  [Themengebiet.ENERGIEDATENMANAGEMENT, 'Energiedatenmanagement'],
  [Themengebiet.FAHRPLANMANAGEMENT, 'Fahrplanmanagement'],
  [Themengebiet.ALOCAT, 'Format:ALOCAT'],
  [Themengebiet.APERAK, 'Format:APERAK'],
  [Themengebiet.CONTRL, 'Format:CONTRL'],
  [Themengebiet.INVOIC, 'Format:INVOIC'],
  [Themengebiet.MSCONS, 'Format:MSCONS'],
  [Themengebiet.ORDERS, 'Format:ORDERS'],
  [Themengebiet.ORDERSP, 'Format:ORDERSP'],
  [Themengebiet.REMADV, 'Format:REMADV'],
  [Themengebiet.UTILMD, 'Format:UTILMD'],
  [Themengebiet.GABI, 'GaBi Gas'],
  [Themengebiet.GELI, 'GeLi Gas'],
  [Themengebiet.GERAETERUECKGABE, 'Geräterückgabe'],
  [Themengebiet.GERAETEWECHSEL, 'Gerätewechsel'],
  [Themengebiet.GPKE, 'GPKE'],
  [Themengebiet.INBETRIEBNAHME, 'Inbetriebnahme'],
  [Themengebiet.KAPAZITAETSMANAGEMENT, 'Kapazitätsmanagement'],
  [Themengebiet.KLAERFAELLE, 'Klärfälle'],
  [Themengebiet.LASTGAENGE_RLM, 'Lastgänge RLM'],
  [Themengebiet.LIEFERANTENRAHMENVERTRAG, 'Lieferantenrahmenvertrag'],
  [Themengebiet.LIEFERANTENWECHSEL, 'Lieferantenwechsel'],
  [Themengebiet.MABIS, 'MaBiS'],
  [Themengebiet.MAHNWESEN, 'Mahnwesen'],
  [Themengebiet.MARKTGEBIETSVERANTWORTLICHER, 'Marktgebietsverantwortlicher'],
  [Themengebiet.MARKTKOMMUNIKATION, 'Marktkommunikation'],
  [Themengebiet.MEHR_MINDERMENGEN, 'Mehr- Mindermengen'],
  [Themengebiet.MSB_MDL, 'MSB - MDL'],
  [Themengebiet.NETZABRECHNUNG, 'Netzabrechnung'],
  [Themengebiet.NETZENTGELTE, 'Netzentgelte'],
  [Themengebiet.NETZMANAGEMENT, 'Netzmanagement'],
  [Themengebiet.RECHT, 'Recht'],
  [Themengebiet.REGULIERUNGSMANAGEMENT, 'Regulierungsmanagement'],
  [Themengebiet.REKLAMATIONEN, 'Reklamationen'],
  [Themengebiet.SPERREN_ENTSPERREN_INKASSO, 'Sperren/Entsperren/Inkasso'],
  [Themengebiet.STAMMDATEN, 'Stammdaten'],
  [Themengebiet.STOERUNGSFAELLE, 'Übermittlung_Störungsfälle'],
  [Themengebiet.TECHNISCHE_FRAGEN, 'Technische Fragen'],
  [Themengebiet.UMSTELLUNG_INVOIC, 'Umstellung INVOIC'],
  [Themengebiet.VERSCHLUESSELUNG_SIGNATUR, 'Verschlüsselung/Signatur'],
  [Themengebiet.VERTRAGSMANAGEMENT, 'Vertragsmanagement'],
  [Themengebiet.VERTRIEB, 'Vertrieb'],
  [Themengebiet.WIM, 'WiM'],
  [Themengebiet.ZAEHLERSTAENDE_SLP, 'Zählerstände SLP'],
  [Themengebiet.ZAHLUNGSVERKEHR, 'Zahlungsverkehr'],
  [Themengebiet.ZUORDNUNGSVEREINBARUNG, 'Zuordnungsvereinbarung'],
]);
