import {EnumLabels} from './util/enum-labels';

/**
 * Aufzählung der Währungscodes.
 *
 * veröffentlicht am 17. Januar 2018
 *
 * @see [ENUM Waehrungscode](https://www.bo4e.de/dokumentation/enumerations/enum-wahrungscode)
 */
export enum Waehrungscode {
    AED = 'AED',
    AFN = 'AFN',
    ALL = 'ALL',
    AMD = 'AMD',
    ANG = 'ANG',
    AOA = 'AOA',
    ARS = 'ARS',
    AUD = 'AUD',
    AWG = 'AWG',
    AZN = 'AZN',
    BAM = 'BAM',
    BBD = 'BBD',
    BDT = 'BDT',
    BGN = 'BGN',
    BHD = 'BHD',
    BIF = 'BIF',
    BMD = 'BMD',
    BND = 'BND',
    BOB = 'BOB',
    BOV = 'BOV',
    BRL = 'BRL',
    BSD = 'BSD',
    BTN = 'BTN',
    BWP = 'BWP',
    BYN = 'BYN',
    BYR = 'BYR',
    BZD = 'BZD',
    CAD = 'CAD',
    CDF = 'CDF',
    CHE = 'CHE',
    CHF = 'CHF',
    CHW = 'CHW',
    CLF = 'CLF',
    CLP = 'CLP',
    CNY = 'CNY',
    COP = 'COP',
    COU = 'COU',
    CRC = 'CRC',
    CUC = 'CUC',
    CUP = 'CUP',
    CVE = 'CVE',
    CZK = 'CZK',
    DJF = 'DJF',
    DKK = 'DKK',
    DOP = 'DOP',
    DZD = 'DZD',
    EGP = 'EGP',
    ERN = 'ERN',
    ETB = 'ETB',
    EUR = 'EUR',
    FJD = 'FJD',
    FKP = 'FKP',
    GBP = 'GBP',
    GEL = 'GEL',
    GHS = 'GHS',
    GIP = 'GIP',
    GMD = 'GMD',
    GNF = 'GNF',
    GTQ = 'GTQ',
    GYD = 'GYD',
    HKD = 'HKD',
    HNL = 'HNL',
    HRK = 'HRK',
    HTG = 'HTG',
    HUF = 'HUF',
    IDR = 'IDR',
    ILS = 'ILS',
    INR = 'INR',
    IQD = 'IQD',
    IRR = 'IRR',
    ISK = 'ISK',
    JMD = 'JMD',
    JOD = 'JOD',
    JPY = 'JPY',
    KES = 'KES',
    KGS = 'KGS',
    KHR = 'KHR',
    KMF = 'KMF',
    KPW = 'KPW',
    KRW = 'KRW',
    KWD = 'KWD',
    KYD = 'KYD',
    KZT = 'KZT',
    LAK = 'LAK',
    LBP = 'LBP',
    LKR = 'LKR',
    LRD = 'LRD',
    LSL = 'LSL',
    LTL = 'LTL',
    LYD = 'LYD',
    MAD = 'MAD',
    MDL = 'MDL',
    MGA = 'MGA',
    MKD = 'MKD',
    MMK = 'MMK',
    MNT = 'MNT',
    MOP = 'MOP',
    MRO = 'MRO',
    MUR = 'MUR',
    MVR = 'MVR',
    MWK = 'MWK',
    MXN = 'MXN',
    MXV = 'MXV',
    MYR = 'MYR',
    MZN = 'MZN',
    NAD = 'NAD',
    NGN = 'NGN',
    NIO = 'NIO',
    NOK = 'NOK',
    NPR = 'NPR',
    NZD = 'NZD',
    OMR = 'OMR',
    PAB = 'PAB',
    PEN = 'PEN',
    PGK = 'PGK',
    PHP = 'PHP',
    PKR = 'PKR',
    PLN = 'PLN',
    PYG = 'PYG',
    QAR = 'QAR',
    RON = 'RON',
    RSD = 'RSD',
    RUB = 'RUB',
    RUR = 'RUR',
    RWF = 'RWF',
    SAR = 'SAR',
    SBD = 'SBD',
    SCR = 'SCR',
    SDG = 'SDG',
    SEK = 'SEK',
    SGD = 'SGD',
    SHP = 'SHP',
    SLL = 'SLL',
    SOS = 'SOS',
    SRD = 'SRD',
    SSP = 'SSP',
    STD = 'STD',
    SVC = 'SVC',
    SYP = 'SYP',
    SZL = 'SZL',
    THB = 'THB',
    TJS = 'TJS',
    TMT = 'TMT',
    TND = 'TND',
    TOP = 'TOP',
    TRY = 'TRY',
    TTD = 'TTD',
    TWD = 'TWD',
    TZS = 'TZS',
    UAH = 'UAH',
    UGX = 'UGX',
    USD = 'USD',
    USN = 'USN',
    USS = 'USS',
    UYI = 'UYI',
    UYU = 'UYU',
    UZS = 'UZS',
    VEF = 'VEF',
    VND = 'VND',
    VUV = 'VUV',
    WST = 'WST',
    XAF = 'XAF',
    XAG = 'XAG',
    XAU = 'XAU',
    XBA = 'XBA',
    XBB = 'XBB',
    XBC = 'XBC',
    XBD = 'XBD',
    XCD = 'XCD',
    XDR = 'XDR',
    XOF = 'XOF',
    XPD = 'XPD',
    XPF = 'XPF',
    XPT = 'XPT',
    XSU = 'XSU',
    XTS = 'XTS',
    XUA = 'XUA',
    XXX = 'XXX',
    YER = 'YER',
    ZAR = 'ZAR',
    ZMW = 'ZMW',
    ZWL = 'ZWL',
}

/**
 * Liefert kurze textuelle Repräsentationen des {@link Waehrungscode}.
 */
export const WaehrungscodeLabel: EnumLabels<Waehrungscode> = EnumLabels.of([
  [Waehrungscode.AED, 'UAE Dirham'],
  [Waehrungscode.AFN, 'Afghani'],
  [Waehrungscode.ALL, 'Lek'],
  [Waehrungscode.AMD, 'Armenian Dram'],
  [Waehrungscode.ANG, 'Netherlands Antillean Guilder'],
  [Waehrungscode.AOA, 'Kwanza'],
  [Waehrungscode.ARS, 'Argentine Peso'],
  [Waehrungscode.AUD, 'Australian Dollar'],
  [Waehrungscode.AWG, 'Aruban Florin'],
  [Waehrungscode.AZN, 'Azerbaijanian Manat'],
  [Waehrungscode.BAM, 'Convertible Mark'],
  [Waehrungscode.BBD, 'Barbados Dollar'],
  [Waehrungscode.BDT, 'Taka'],
  [Waehrungscode.BGN, 'Bulgarian Lev'],
  [Waehrungscode.BHD, 'Bahraini Dinar'],
  [Waehrungscode.BIF, 'Burundi Franc'],
  [Waehrungscode.BMD, 'Bermudian Dollar'],
  [Waehrungscode.BND, 'Brunei Dollar'],
  [Waehrungscode.BOB, 'Boliviano'],
  [Waehrungscode.BOV, 'Mvdol'],
  [Waehrungscode.BRL, 'Brazilian Real'],
  [Waehrungscode.BSD, 'Bahamian Dollar'],
  [Waehrungscode.BTN, 'Ngultrum'],
  [Waehrungscode.BWP, 'Pula'],
  [Waehrungscode.BYN, 'Belarusian Ruble'],
  [Waehrungscode.BYR, 'Belarusian Ruble'],
  [Waehrungscode.BZD, 'Belize Dollar'],
  [Waehrungscode.CAD, 'Canadian Dollar'],
  [Waehrungscode.CDF, 'Congolese Franc'],
  [Waehrungscode.CHE, 'WIR Euro'],
  [Waehrungscode.CHF, 'Swiss Franc'],
  [Waehrungscode.CHW, 'WIR Franc'],
  [Waehrungscode.CLF, 'Unidad de Fomento'],
  [Waehrungscode.CLP, 'Chilean Peso'],
  [Waehrungscode.CNY, 'Yuan Renminbi'],
  [Waehrungscode.COP, 'Colombian Peso'],
  [Waehrungscode.COU, 'Unidad de Valor Real'],
  [Waehrungscode.CRC, 'Costa Rican Colon'],
  [Waehrungscode.CUC, 'Peso Convertible'],
  [Waehrungscode.CUP, 'Cuban Peso'],
  [Waehrungscode.CVE, 'Cape Verde Escudo'],
  [Waehrungscode.CZK, 'Czech Koruna'],
  [Waehrungscode.DJF, 'Djibouti Franc'],
  [Waehrungscode.DKK, 'Danish Krone'],
  [Waehrungscode.DOP, 'Dominican Peso'],
  [Waehrungscode.DZD, 'Algerian Dinar'],
  [Waehrungscode.EGP, 'Egyptian Pound'],
  [Waehrungscode.ERN, 'Nakfa'],
  [Waehrungscode.ETB, 'Ethiopian Birr'],
  [Waehrungscode.EUR, 'Euro'],
  [Waehrungscode.FJD, 'Fiji Dollar'],
  [Waehrungscode.FKP, 'Falkland Islands Pound'],
  [Waehrungscode.GBP, 'Pound Sterling'],
  [Waehrungscode.GEL, 'Lari'],
  [Waehrungscode.GHS, 'Ghana Cedi'],
  [Waehrungscode.GIP, 'Gibraltar Pound'],
  [Waehrungscode.GMD, 'Dalasi'],
  [Waehrungscode.GNF, 'Guinea Franc'],
  [Waehrungscode.GTQ, 'Quetzal'],
  [Waehrungscode.GYD, 'Guyana Dollar'],
  [Waehrungscode.HKD, 'Hong Kong Dollar'],
  [Waehrungscode.HNL, 'Lempira'],
  [Waehrungscode.HRK, 'Croatian Kuna'],
  [Waehrungscode.HTG, 'Gourde'],
  [Waehrungscode.HUF, 'Forint'],
  [Waehrungscode.IDR, 'Rupiah'],
  [Waehrungscode.ILS, 'New Israeli Sheqel'],
  [Waehrungscode.INR, 'Indian Rupee'],
  [Waehrungscode.IQD, 'Iraqi Dinar'],
  [Waehrungscode.IRR, 'Iranian Rial'],
  [Waehrungscode.ISK, 'Iceland Krona'],
  [Waehrungscode.JMD, 'Jamaican Dollar'],
  [Waehrungscode.JOD, 'Jordanian Dinar'],
  [Waehrungscode.JPY, 'Yen'],
  [Waehrungscode.KES, 'Kenyan Shilling'],
  [Waehrungscode.KGS, 'Som'],
  [Waehrungscode.KHR, 'Riel'],
  [Waehrungscode.KMF, 'Comoro Franc'],
  [Waehrungscode.KPW, 'North Korean Won'],
  [Waehrungscode.KRW, 'Won'],
  [Waehrungscode.KWD, 'Kuwaiti Dinar'],
  [Waehrungscode.KYD, 'Cayman Islands Dollar'],
  [Waehrungscode.KZT, 'Tenge'],
  [Waehrungscode.LAK, 'Kip'],
  [Waehrungscode.LBP, 'Lebanese Pound'],
  [Waehrungscode.LKR, 'Sri Lanka Rupee'],
  [Waehrungscode.LRD, 'Liberian Dollar'],
  [Waehrungscode.LSL, 'Loti'],
  [Waehrungscode.LTL, 'Lithuanian Litas'],
  [Waehrungscode.LYD, 'Libyan Dinar'],
  [Waehrungscode.MAD, 'Moroccan Dirham'],
  [Waehrungscode.MDL, 'Moldovan Leu'],
  [Waehrungscode.MGA, 'Malagasy Ariary'],
  [Waehrungscode.MKD, 'Denar'],
  [Waehrungscode.MMK, 'Kyat'],
  [Waehrungscode.MNT, 'Tugrik'],
  [Waehrungscode.MOP, 'Pataca'],
  [Waehrungscode.MRO, 'Ouguiya'],
  [Waehrungscode.MUR, 'Mauritius Rupee'],
  [Waehrungscode.MVR, 'Rufiyaa'],
  [Waehrungscode.MWK, 'Kwacha'],
  [Waehrungscode.MXN, 'Mexican Peso'],
  [Waehrungscode.MXV, 'Mexican Unidad de Inversion (UDI)'],
  [Waehrungscode.MYR, 'Malaysian Ringgit'],
  [Waehrungscode.MZN, 'Mozambique Metical'],
  [Waehrungscode.NAD, 'Namibia Dollar'],
  [Waehrungscode.NGN, 'Naira'],
  [Waehrungscode.NIO, 'Cordoba Oro'],
  [Waehrungscode.NOK, 'Norwegian Krone'],
  [Waehrungscode.NPR, 'Nepalese Rupee'],
  [Waehrungscode.NZD, 'New Zealand Dollar'],
  [Waehrungscode.OMR, 'Rial Omani'],
  [Waehrungscode.PAB, 'Balboa'],
  [Waehrungscode.PEN, 'Nuevo Sol'],
  [Waehrungscode.PGK, 'Kina'],
  [Waehrungscode.PHP, 'Philippine Peso'],
  [Waehrungscode.PKR, 'Pakistan Rupee'],
  [Waehrungscode.PLN, 'Zloty'],
  [Waehrungscode.PYG, 'Guarani'],
  [Waehrungscode.QAR, 'Qatari Rial'],
  [Waehrungscode.RON, 'New Romanian Leu'],
  [Waehrungscode.RSD, 'Serbian Dinar'],
  [Waehrungscode.RUB, 'Russian Ruble'],
  [Waehrungscode.RUR, 'Russian Ruble'],
  [Waehrungscode.RWF, 'Rwanda Franc'],
  [Waehrungscode.SAR, 'Saudi Riyal'],
  [Waehrungscode.SBD, 'Solomon Islands Dollar'],
  [Waehrungscode.SCR, 'Seychelles Rupee'],
  [Waehrungscode.SDG, 'Sudanese Pound'],
  [Waehrungscode.SEK, 'Swedish Krona'],
  [Waehrungscode.SGD, 'Singapore Dollar'],
  [Waehrungscode.SHP, 'Saint Helena Pound'],
  [Waehrungscode.SLL, 'Leone'],
  [Waehrungscode.SOS, 'Somali Shilling'],
  [Waehrungscode.SRD, 'Surinam Dollar'],
  [Waehrungscode.SSP, 'South Sudanese Pound'],
  [Waehrungscode.STD, 'Dobra'],
  [Waehrungscode.SVC, 'El Salvador Colon'],
  [Waehrungscode.SYP, 'Syrian Pound'],
  [Waehrungscode.SZL, 'Lilangeni'],
  [Waehrungscode.THB, 'Baht'],
  [Waehrungscode.TJS, 'Somoni'],
  [Waehrungscode.TMT, 'Turkmenistan New Manat'],
  [Waehrungscode.TND, 'Tunisian Dinar'],
  [Waehrungscode.TOP, 'PaÊ»anga'],
  [Waehrungscode.TRY, 'Turkish Lira'],
  [Waehrungscode.TTD, 'Trinidad and Tobago Dollar'],
  [Waehrungscode.TWD, 'New Taiwan Dollar'],
  [Waehrungscode.TZS, 'Tanzanian Shilling'],
  [Waehrungscode.UAH, 'Hryvnia'],
  [Waehrungscode.UGX, 'Uganda Shilling'],
  [Waehrungscode.USD, 'US Dollar'],
  [Waehrungscode.USN, 'US Dollar (Next day)'],
  [Waehrungscode.USS, 'US Dollar (Same day)'],
  [Waehrungscode.UYI, 'Uruguay Peso en Unidades Indexadas (URUIURUI)'],
  [Waehrungscode.UYU, 'Peso Uruguayo'],
  [Waehrungscode.UZS, 'Uzbekistan Sum'],
  [Waehrungscode.VEF, 'Bolivar'],
  [Waehrungscode.VND, 'Dong'],
  [Waehrungscode.VUV, 'Vatu'],
  [Waehrungscode.WST, 'Tala'],
  [Waehrungscode.XAF, 'CFA Franc BEAC'],
  [Waehrungscode.XAG, 'Silver'],
  [Waehrungscode.XAU, 'Gold'],
  [Waehrungscode.XBA, 'Bond Markets Unit European Composite Unit (EURCO)'],
  [Waehrungscode.XBB, 'Bond Markets Unit European Monetary Unit (E.M.U.-6)'],
  [Waehrungscode.XBC, 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)'],
  [Waehrungscode.XBD, 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)'],
  [Waehrungscode.XCD, 'East Caribbean Dollar'],
  [Waehrungscode.XDR, 'SDR (Special Drawing Right)'],
  [Waehrungscode.XOF, 'CFA Franc BCEAO'],
  [Waehrungscode.XPD, 'Palladium'],
  [Waehrungscode.XPF, 'CFP Franc'],
  [Waehrungscode.XPT, 'Platinum'],
  [Waehrungscode.XSU, 'Sucre'],
  [Waehrungscode.XTS, 'Codes specifically reserved for testing purposes'],
  [Waehrungscode.XUA, 'ADB Unit of Account'],
  [Waehrungscode.XXX, 'The codes assigned for transactions where no currency ist involved'],
  [Waehrungscode.YER, 'Yemeni Rial'],
  [Waehrungscode.ZAR, 'Rand'],
  [Waehrungscode.ZMW, 'Zambian Kwacha'],
  [Waehrungscode.ZWL, 'Zimbabwe Dollar'],
]);
